version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: infra/backend.Dockerfile
    env_file:
      - ../config/.env.example
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ..
      dockerfile: infra/frontend.Dockerfile
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
  gypsycove:
    build:
      context: ..
      dockerfile: infra/gypsycove.Dockerfile
    env_file:
      - ../config/.env.example
    ports:
      - "8100:8100"